---
title: "Medical statistics"
output: html_document
date: "2025-07-05"
---

```{r}
library(tidyverse)
library(janitor)
library(haven)
library(epitools)
```

# Measures of association
## Confidence intervals for relative risk

Relative risk

```{r}
a <- 1934
n1 <- 142870
c <- 2894
n2 = 392757

rr <- (a/n1)/(c/n2)

rr
```

Estimated standard error

```{r}
s <- sqrt(1/a - 1/n1 + 1/c - 1/n2)
s
```

Confidence interval

```{r}
alpha <- 0.01
z <- qnorm(1 - alpha/2)

ci <- c(rr * exp(-z * s), rr * exp(z * s))
ci
```

## Confidence intervals for odds ratio

Relative risk

```{r}
a <- 35
b <- 34
c <- 153
d <- 637

or <- (a*d)/(b*c)

or
```

Estimated standard error

```{r}
s <- sqrt(1/a + 1/b + 1/c + 1/d)
s
```

Confidence interval

```{r}
alpha <- 0.05
z <- qnorm(1 - alpha/2)

ci <- c(or * exp(-z * s), or * exp(z * s))
ci
```


## Chi-squared distribution

```{r}
df <- tibble(x = seq(0.1, 10, 0.1)) %>%
  mutate(`1` = dchisq(x, 1),
         `2` = dchisq(x, 2),
         `3` = dchisq(x, 3),
         `4` = dchisq(x, 4),
         `5` = dchisq(x, 5),) %>%
  pivot_longer(cols = -x, names_to = "df", values_to = "d")

ggplot(df, aes(x = x, y = d, group = df, colour = df)) + geom_line() + theme_minimal()
```



## Cross tabulation

```{r}
df_eclampsia <- tibble(count = c(327, 215, 76, 201), exposure = c(1,1,2,2), disease = c(1,2,1,2)) %>%
  mutate(exposure = factor(exposure, levels = c(1, 2), labels = c("eclampsia", "no eclampsia")),
         disease = factor(disease, levels = c(1, 2), labels = c("hypertension", "no hypertension")))
df_eclampsia
```

```{r}
tab_eclampsia <- xtabs(count ~ exposure + disease, data = df_eclampsia)
addmargins(tab_eclampsia)
```


## Cohort studies

```{r}
df_redundancy <- read_sav("data/Book 1/redundancy.sav") %>%
  mutate(exposure = factor(exposure, levels = c(1, 2), labels = c("redundant", "not_redundant")),
         disease = factor(disease, levels = c(1, 2), labels = c("injury", "no_injury")))
```

```{r}
tab_redundancy <- xtabs(count ~ exposure + disease, data = df_redundancy)
addmargins(tab_redundancy)
```
```{r}
epiR::epi.2by2(tab_redundancy, method = "cohort.count")
```


